apiVersion: v1
kind: Pod
metadata:
  name: mcnt
  namespace: test
  labels:
    name: mcnt
spec:
  containers:
  - name: mcnt
    image: nginx:1.15.10
    ports:
        - containerPort: 80

  - name: mcnt2
    image: bitnami/apache
    ports:
        - containerPort: 81