apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:

  containers:
  - name: con1
    image: nginx
  - name: con2
    image: debian
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 1;
        done