apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi
  name: multi
spec:
  containers:
  - image: nginx:alpine
    name: nginx
    ports:
      - containerPort: 81
    
  - image: bitnami/apache
    name: apache
    ports:
      - containerPort: 8080
 
