kind: Service
apiVersion: v1
metadata:
  name: mcd-deployment
  labels: 
    app: mcd
spec:
  type: NodePort
  selector:
    app: mcd
  ports:
  - name: nginx
    protocol: TCP
    port: 80
    
  - name: apache
    protocol: TCP
    port: 30
    